### ISSUE TITLE
avoiding low-level grid unit access

### ISSUE THREAD

**Issue by pmur002** [eliocamp/metR#104]
Hi

In geom_arrow.R (and aslight variation in geom_streamline.R) , you have ...
```
  arrow$length <- unit(as.numeric(arrow$length)*mag, attr(arrow$length, "unit"))
```
... which will fail if we change the internal implementation of 'grid' units (which is something we are currently trying out).  I believe your code could (and should) be replaced by ...
```
  arrow$length <- mag*arrow$length
```
Paul

**Comment by eliocamp** [comment]
Hi, Paul! Thanks for the heads up. 
I've tried the change and realised that there was a reason I went with that circuitous route. This is how it works now:

``` r
library(data.table)
library(ggplot2)

data(seals)

ggplot(seals, aes(long, lat)) +
    geom_vector(aes(dx = delta_long, dy = delta_lat), skip = 1) +
    scale_mag()
```

![image](https://user-images.githubusercontent.com/8617595/66223386-bd38f980-e6a9-11e9-9786-ecbcf6cf8e36.png)

Note that arrow lengths are proportional to magnitude. 

And here's how it works out using the simpler code:

![image](https://user-images.githubusercontent.com/8617595/66223473-f70a0000-e6a9-11e9-8efb-3401b3dddd0b.png)

Note that they are all the same length.

**Comment by pmur002** [comment]
Thanks for checking this out.  

The below is what I get from your code above ...
![Rplot001](https://user-images.githubusercontent.com/2044052/66280940-9bdc4580-e915-11e9-8d45-6591acf84562.png)
... and that is with the attached package [metR_0.4.0.tar.gz](https://github.com/eliocamp/metR/files/3695284/metR_0.4.0.tar.gz), which has this code on line 217 of geom_arrow.R ...
```
     arrow$length <- mag*arrow$length
```

Is that the same as the change that you tried ?

**Comment by eliocamp** [comment]
Yes, it's exactly what I've changed. That's very weird that you get a different result :thinking: 

I've created a branch with the change. Do you get the same result?
Skipping
``` r
library(data.table)
library(ggplot2)
library(metR) # devtools::install_github("eliocamp/metR@grid-arrow")

data(seals)

ggplot(seals, aes(long, lat)) +
    geom_vector(aes(dx = delta_long, dy = delta_lat), skip = 1) +
    scale_mag()
```

![](https://i.imgur.com/7OO6yGb.png)

<sup>Created on 2019-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pmur002** [comment]
Thanks for sticking with this.  I have found the (glaring) difference in what I am doing.  If I run your example with the 'metR' branch on the current r-devel R version I get the same as you ...
![metR-grid-arrow](https://user-images.githubusercontent.com/2044052/66354204-938d1480-e9c0-11e9-9126-73f3f98b8e1e.png)
It is only when I run the 'metR' branch on the R version I have with the new 'grid' unit implementation that I get the right result ...
![metR-grid-arrow-new-units](https://user-images.githubusercontent.com/2044052/66354248-b28ba680-e9c0-11e9-9ebb-767890ef5528.png)

So this is hopefully a useful modification to keep in hand for when (if) we shift over to the new units in 'grid' in an R release, but not a good idea to do yet.

Thanks again for engaging with this suggestion.

**Comment by eliocamp** [comment]
Thanks! 
Then I should add a check for the grid version when the new implementation come out. Do you know which version number will feature the change?

**Comment by pmur002** [comment]
Sorry, it is not certain yet.  I will be in touch once we know which R version this will be in.

**Comment by eliocamp** [comment]
Awesome. As soon as it does, I'll add the fix. 
Thanks again!
