### ISSUE TITLE
Usar en otro package la función ReadNetCDF

### ISSUE THREAD

**Issue by lemuscanovas** [eliocamp/metR#106]
Hola Elio! 
Tengo en mente crear un package que necesita de tu función `ReadNetCDF` para leer los ficheros de entrada, pero es que ni tan solo quiero modificarla (me parece impecable). ¿Es posible qué cuándo cree mi paquete, pueda llamar a tu función y se cargue con las demás funciones de mi paquete? El problema que veo es que no puedo documentar en mi paquete una función que ya está creada y documentada.
Quiero que quede claro que esta función es del paquete metR.

No sé si me he explicado muy bién. 

En todo caso, gracias por está función. Creo que nunca había sido tan fácil jugar con un .nc

Saludos,
Marc

**Comment by eliocamp** [comment]
Hola! Gracias por las amables palabras! 😁

No entiendo bien de qué forma necesitarías depender de metR. Si es que tu paquete es para tomar datos de netcdf y procesarlos de alguna manera, y que es el usuario el que usa la función, lo más razonable para mí sería que no hagas una dependencia explícita. Que el usuario de tu paquete lea los datos como quiera. Luego podés recomendar ReadNetCDF en la documentación de la función o en las viñetas. Eso es lo más "limpio" ya que agregar a metR de dependencia implica que agregas como dependencias también todas las dependencias de metR (si se entiende) que por ahora son muchas (por falla mía, en realidad, y con suerte reduciéndose en el futuro próximo). 


Por otro lado, si ReadNetCDF es una función interna de tu paquete, entonces no hace falta que la documentes. Simplemente agregas a metR como dependencia y usas ReadNetCDF dentro de tu paquete.

**Comment by lemuscanovas** [comment]
Gracias por la resupuesta Elio, usaré externamente tu función.

Y disculpa la demora en la respuesta.
Saludos,
Marc

**Comment by eliocamp** [comment]
Perfecto, entonces mi recomendación es esa, ¿te parece bien?
