### ISSUE TITLE
Error in WaveFlux function

### ISSUE THREAD

**Issue by salvatirehbein** [eliocamp/metR#110]
I found the following problem trying to use the WaveFlux function (**ps** not found):

`Error in eval(predvars, data, env) : objeto 'ps' não encontrado`

I think that it should be **psi**  instead of **ps**  in the 2nd line below:  

```
dt[, `:=`(psi.dx = Derivate(psi ~ lonrad, cyclical = TRUE), 
        psi.dxx = Derivate(ps ~ lonrad, 2), cyclical = TRUE), 
        by = lat]
```

**Comment by eliocamp** [comment]
Thanks! 
That poor function is a bit orphaned since I'm now using another function to compute wave activity fluxes using streamfunction from reanalysis directly, which is the better way, I think. 
It might need some love. There are a lot of other formulas with various assumptions.
