### ISSUE TITLE
Adding scale and offset when reading a variable

### ISSUE THREAD

**Issue by paocorrales** [eliocamp/metR#115]
I just found out that the NetCDF library automatically read the _scale_ and _offset_ attributes of a variable and applied them to the variable along the reading process.

It would be great if `ReadNetCDF()` had this feature!

**Comment by eliocamp** [comment]
Thanks! 
The current development version now supports this feature. You need to wrap the variable name you want to scale in an `auto_scale()` call (e.g. `ReadNetCDF(file, vars = auto_scale("variable"))`).
