### ISSUE TITLE
scale_mag() name and guide arguments not working?

### ISSUE THREAD

**Issue by makratofil** [eliocamp/metR#120]
Hi Elio,

I'm plotting vectors using geom_vector() and want to change the title of the legend to be more descriptive (instead of 'mag'). 

I've tried using the 'name' argument within scale_mag(): 
```
ggplot() +
geom_vector(data, aes(dx, dy), skip.x = 2, skip.y = 1, preserve.dir = TRUE, colour = 'white',
show.legend = TRUE) +
scale_mag(name = "Velocity (m/s)")

```
And the 'guide argument':
```
ggplot() +
geom_vector(data, aes(dx, dy), skip.x = 2, skip.y = 1, preserve.dir = TRUE, colour = 'white',
show.legend = TRUE) +
scale_mag(guide = guide_legend(title = "Velocity (m/s)"))

```
And neither have worked. I was wondering if there is a more appropriate way to do this, or if this is a bug?

Thank you for your time!

**Comment by pascaloettli** [comment]
It is a bug of `scale_mag` in version `0.6.0` of `metR`
Using the example script in `?scale_mag`

```
library(ggplot2)
library(metR)
library(gridExtra)

g <- ggplot(seals, aes(long, lat)) +
  geom_vector(aes(dx = delta_long, dy = delta_lat), skip = 2)

g1 <- g + scale_mag("Seals velocity")

g2 <- g + scale_mag("Seals velocity", max = 1)

g3 <- g + scale_mag("Seals velocity", max_size = 2)
g4 <- g + scale_mag("Seals velocity", default_unit = "mm")

grid.arrange(g1, g2, g3, g4)
```

Version `0.5.0`
![plot_zoom_png_0 5 0](https://user-images.githubusercontent.com/6613954/84452806-d317a900-ac91-11ea-9149-5990585e92cf.png)

Version `0.6.0`
![plot_zoom_png_0 6 0](https://user-images.githubusercontent.com/6613954/84452801-d14de580-ac91-11ea-9d0b-f60daaeb3946.png)

**Comment by makratofil** [comment]
@pascaloettli Thanks! I was able to get this to work by installing the older version.

**Comment by eliocamp** [comment]
Thanks! I'm looking into it!

**Comment by eliocamp** [comment]
Hi!
This is now fixed in the dev version. 

Thanks for the report!
