### ISSUE TITLE
stat_subset densidad de puntos

### ISSUE THREAD

**Issue by lemuscanovas** [eliocamp/metR#134]
Hola Elio,

Una consulta rápida, en el ejemplo que tienes en el uso de `stat_subset`:

```r 
data(geopotential)    # geopotential height at 700hPa for the Southern Hemisphere. 

ggplot(geopotential[, gh.base := gh[lon == 120 & lat == -50], by = date][
    , .(correlation = cor(gh.base, gh)), 
    by = .(lon, lat)],
    aes(lon, lat, z = correlation)) +
    geom_contour_fill(breaks = MakeBreaks(0.1)) +
    stat_subset(aes(subset = correlation > 0.5),
                geom = "point", size = 0.1) +
    scale_fill_divergent() 
```

¿Hay alguna manera para reducir la densidad de puntos? En el ejemplo no hay problema porque se trata de un grid de baja resolución, pero si se usa una rejilla de alta resolución hay demasiados puntos.

Gracias de antemano,
Marc

**Comment by eliocamp** [comment]
Sí, fijate la función [`is.cross()`](https://eliocamp.github.io/metR/reference/is.cross.html), que a partir de una grilla regular, te devuelve los puntos que forman una "cruz"

```r
library(ggplot2)
ggplot(temperature[lev == 500], aes(lon, lat)) +
  geom_raster(aes(fill = air)) +
  stat_subset(aes(subset = air > 270 & is.cross(lon, lat)),
              geom = "point", size = 0.1)
```
![](https://eliocamp.github.io/metR/reference/is.cross-2.png)

**Comment by lemuscanovas** [comment]
Brutal! Muchísimas gracias por la rapidez en la respuesta!

**Comment by eliocamp** [comment]
De nada!
