### ISSUE TITLE
geom_contour_tanaka shading incoherently

### ISSUE THREAD

**Issue by Oblarg** [eliocamp/metR#137]
I have a baseball statistics tool that I'm working on, and I'm attempting to use `geom_contour_tanaka` for some plots.  Alas, the shading does not appear to be working properly:

![image](https://user-images.githubusercontent.com/23393863/107445627-d60db680-6b0a-11eb-8760-3a498e0653d3.png)

![image](https://user-images.githubusercontent.com/23393863/107445568-b7a7bb00-6b0a-11eb-8dd8-ba1cb2c6ceba.png)

If you look closely, you'll see that `geom_contour_tanaka` seems to disagree with the color fill (and, I think, with the data) as to whether a given level should be "popped out" or "popped in."  In fact, it doesn't even appear to be locally-consistent with itself.

Any idea what could causing this on my end, or is this a bug?

The relevant call is:

```R
ggplot(dat, aes_string(x = "launch_speed", y = "launch_angle", z = plotVariable)) +
      geom_contour_filled(breaks = breaks) +
      geom_contour_tanaka(breaks = breaks) +
      scale_fill_manual(values = colors, drop = FALSE) +
      coord_polar(theta = "y",
                  start = pi / 2,
                  direction = -1) +
      scale_y_continuous(
          breaks = seq(-90, 90, by = 10),
          minor_breaks = NULL,
          limits = c(-180, 180)
      ) +
      scale_x_continuous(breaks = seq(0, 120, by = 10),
                         limits = c(0, 120)) +
      labs(
          x = "Launch speed",
          y = "Launch angle",
          fill = plotVariable,
          caption = caption[[plotVariable]]
      )
```

**Comment by eliocamp** [comment]
Are you using the latest version? 
Can you send me the relevant data that reproduces those plots?

**Comment by Oblarg** [comment]
Updating to the most recent version produces the following error:

```Warning: Computation failed in `stat_contour2()`:
object 'rlang_hash' not found```

I could try to provide the data, but it'd take some work to wrangle it into a shareable format.

**Comment by eliocamp** [comment]
That looks to be some kind of issue with your installation of the rlang package. If you haven't yet restarted your R session, do it and try again. If it still doesn't work, try reinstalling the rlang package (`install.packages("rlang")`), restarting your session and trying again.

**Comment by Oblarg** [comment]
That appears to have fixed it.  Thanks!

**Comment by eliocamp** [comment]
Great! And the contours work as expected?

**Comment by Oblarg** [comment]
Yep.
