### ISSUE TITLE
Falta alguna dependencia?

### ISSUE THREAD

**Issue by lemuscanovas** [eliocamp/metR#138]
Hola Elio! 

Jugando un poco con tu librería, básicamente cuando uso `geom_contour2` o `geom_text_contour`, me he encontrado con el siguiente warning que impide plotear las isolineas y las etiquetas:

```r
Warning: namespace ‘fastmap’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
Warning: namespace ‘cachem’ is not available and has been replaced
by .GlobalEnv when processing object ‘<unknown>’
```
También parece que echa en falta la función ` 'rlang_hash`

```r
Computation failed in `stat_text_contour()`:
object 'rlang_hash' not found
```
Si se instala `fastmap`, `cachem` y `rlang`, todo vueleve a estar en orden!
Saludos
Marc

**Comment by eliocamp** [comment]
Parecería ser algo parecido a esto: https://github.com/eliocamp/metR/issues/137#issuecomment-776372690. 
Parece ser algún problema con el paquete rlang que se arregla reinstalándolo (o actualizándolo)
