### ISSUE TITLE
Wrong default for expand in latitude and longitude scales

### ISSUE THREAD

**Issue by tamas-ferenci** [eliocamp/metR#167]
The `expand` parameter for the latitude and longitude scales (e.g., `scale_x_longitude`) is said to have a default "to expand the scale by 5% on each side for continuous variables, and by 0.6 units on each side for discrete variables". However, in reality, it is set to a zero expansion by default.

**Comment by eliocamp** [comment]
Ah, yes. This is because I blindly import the documentation from ggplot2. Nice catch.
