### ISSUE TITLE
contour over a map

### ISSUE THREAD

**Issue by fipoucat** [eliocamp/metR#175]
Hi there,

I want to replicate a map with contours of correlations in a dataframe. Then use a specific color (ex green) to color region with 95% confidence interval using metR. an example attached
![corr_precip](https://github.com/eliocamp/metR/assets/3116845/b440f335-f9f4-41dd-8a2f-c309335b606b)

**Comment by eliocamp** [comment]
I don't understand what you mean by colouring the 95% interval. If you are saying that you want to shade correlations that are different from zero with 95% confidence you can use `geom_contour_fill(aes(z = pval), colour = "green", breaks = c(0, 0.05))` to fill zones with p-values smaller than 0.05 (you can also chose whatever cut-off you like; this assumes that you have a `pval` column).

**Comment by fipoucat** [comment]
@eliocamp You comment is correct and reflects what I am trying to do. I have first to create a dataframe with lon lat pr mi
where mi is my monsoon index (seaonal) and seasonal (pr), I then have tor compute the correlation (rr). It's this I want to contour on the map and shade areas with 95% confidence interval. the rainfall data is gridded but the mi index is one value per season.
