### ISSUE TITLE
rgdal archived

### ISSUE THREAD

**Issue by rsbivand** [eliocamp/metR#179]
@eliocamp rgdal was archived yesterday, but is still suggested in metR, so please do move to submit an updated version of metR as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details, see also #169

**Comment by eliocamp** [comment]
Thank you. I though I had removed all the dependencies, but now I see that I was still using raster and gdal.

**Comment by rsbivand** [comment]
raster uses terra, not rgdal, it changed in September 2022, so try just dropping rgdal, and seeing if the resulting packages checks properly (it may need terra in suggests if it doesn't check OK with `R_CHECK_SUGGESTS_ONLY=true`, see https://r-spatial.github.io/evolution/ogh23_bivand.html#Dependencies_between_R_packages.
