### ISSUE TITLE
guide_colorsteps() doesn't work as expected

### ISSUE THREAD

**Issue by pascaloettli** [eliocamp/metR#188]
Trying to reproduce the example of [discretised_scale()](https://eliocamp.github.io/metR/articles/Visualization-tools.html#scales), it fails to produce the correct result:

```
library(metR)
library(ggplot2)
library(data.table)
temperature <- copy(temperature)
temperature[, air.z := Anomaly(air), by = .(lat, lev)]

ggplot(temperature[lev == 300], aes(lon, lat, z = air.z)) +
  geom_contour_fill(aes(fill = after_stat(level)), breaks = c(-10, -8, -6, -2, -1, 0, 6, 8, 10)) +
  guides(fill = guide_colorsteps())

```

![Rplot12](https://github.com/eliocamp/metR/assets/6613954/be18c678-47b7-4590-ae0e-eab8ebcf9856)

ggplot2_3.5.0
metR_0.15.0

**Comment by pascaloettli** [comment]
`ggplot2 3.5.0` breaks the function. It works as expected with `ggplot2 3.4.4`

![Rplot13](https://github.com/eliocamp/metR/assets/6613954/1e508ad5-cee7-4a36-a36c-06cdd8276d89)

**Comment by eliocamp** [comment]
`guide_colorsteps()` is a ggplot2 function. The changes in the guide system seem to have messed it up somehow. Here's an pure ggplot2 example:

``` r
library(ggplot2)
levels <- pretty(range(volcano))

volcano2 <- reshape2::melt(volcano) |> 
  transform(value_discrete = cut(value, 
                                 breaks = levels,
                                 ordered_result = TRUE))

ggplot(volcano2, aes(Var1, Var2)) +
  geom_raster(aes(fill = value_discrete)) 
```

![](https://i.imgur.com/FZhM6uR.png)

``` r
ggplot(volcano2,  aes(Var1, Var2)) +
  geom_raster(aes(fill = value_discrete)) +
  guides(fill = guide_colorsteps())
```

![](https://i.imgur.com/IYNFMl9.png)

<sup>Created on 2024-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I opened an issue on their repo, which you can follow here: https://github.com/tidyverse/ggplot2/issues/5786

**Comment by eliocamp** [comment]
BTW, this has been fixed in the development version of ggplot2

**Comment by pascaloettli** [comment]
Sorry, I missed the fact is was a ggplot2 function and not a metR function. Sorry for the annoyance
