### ISSUE TITLE
Line fill with a slope for parts of the area

### ISSUE THREAD

**Issue by Breeze-Hu** [eliocamp/metR#195]
Dear Elio Campitelli,

In trying to use R for mapping in the field of climate and environment, I found a lot of inconveniences compared to matplotlib in python. I was pleasantly surprised to find that the package you developed provides a lot of useful functions for this purpose. Thank you very much!
Currently I need to draw a plot that contains a color fill and hatch fill, similar to the one below:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/fa8e4634-77b4-45d5-b4a1-a8ed36f81c24">

My current approach is the stat_subset function for conditional filtering, but I'm having trouble drawing the line. The closest I've gotten so far is to use 'geom = 'spoke'', but the length of the line gets out of range due to the radius setting, which is also weird. I wonder if you have a better solution?

radius = 1:
<img width="201" alt="image" src="https://github.com/user-attachments/assets/09e6d2c4-c578-4ca9-a89c-e040f09f5b08">
radius = 0.2:
<img width="123" alt="image" src="https://github.com/user-attachments/assets/74404a0f-ee21-4ef6-ba2c-43560c376ba6">

best wishes，
Hu

**Comment by eliocamp** [comment]
You  might want to take a look at ggpattern: https://coolbutuseless.github.io/package/ggpattern/

You can use `stat_contour_fill(geom = ggpattern::GeomPolygonPattern))` and change the pattern options to get something that looks like what you want.
