### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by rmendels** [eliocamp/metR#73]
> devtools::install_github("eliocamp/metR")
Downloading GitHub repo eliocamp/metR@master
from URL https://api.github.com/repos/eliocamp/metR/zipball/master
Installation failed: Command failed (50)

**Comment by eliocamp** [comment]
Is that the whole error message? It's seems a problem with install_github, maybe it failed to download (it happens sometimes).
Did you try again? Can you download manually from that link?

**Comment by rmendels** [comment]
I was able to install by downloading and installing locally,  but had to install formula.tools first.

**Comment by eliocamp** [comment]
Great! 
I believe this might have been a problem on `devtools` side or (more likely) some internet connectivity glitch. If more people report a similar problem, then it could mean a bug on my end. So thanks for reporting the issue :)
