### ISSUE TITLE
Size of arrow head using facet_wrap or facet_grid

### ISSUE THREAD

**Issue by m-saenger** [eliocamp/metR#92]
I noticed that the the size of the arrow head does not scale across different facet panels. In the example below the arrows denoted with a red point have the same underlying vector (u = 9, v = 9). However, the size of the arrow head is different. 

Thanks

``` r
library(ggplot2)
library(metR)

dt <- expand.grid(x = 1:3, y = 1:3, class = c("Normal Size", "Triple Size"))
dt$u = c(1:9, 1:9*3)
dt$v = c(1:9, 1:9*3)

g <- ggplot(dt, aes(x, y)) +
  facet_wrap("class") +
  geom_vector(aes(dx = u, dy = v)) +
  geom_point(data = dt[which(dt$u == 9 & dt$v == 9),], colour = "red", size = 3) +
  theme_minimal() + 
  coord_equal(xlim = c(0, 4), ylim = c(0, 4))
  
g + scale_mag(max_size = 3)
```

![](https://i.imgur.com/f0QDmTS.png)

``` r
print(dt)
#>    x y       class  u  v
#> 1  1 1 Normal Size  1  1
#> 2  2 1 Normal Size  2  2
#> 3  3 1 Normal Size  3  3
#> 4  1 2 Normal Size  4  4
#> 5  2 2 Normal Size  5  5
#> 6  3 2 Normal Size  6  6
#> 7  1 3 Normal Size  7  7
#> 8  2 3 Normal Size  8  8
#> 9  3 3 Normal Size  9  9
#> 10 1 1 Triple Size  3  3
#> 11 2 1 Triple Size  6  6
#> 12 3 1 Triple Size  9  9
#> 13 1 2 Triple Size 12 12
#> 14 2 2 Triple Size 15 15
#> 15 3 2 Triple Size 18 18
#> 16 1 3 Triple Size 21 21
#> 17 2 3 Triple Size 24 24
#> 18 3 3 Triple Size 27 27
```

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by eliocamp** [comment]
Good catch. Right now arrow size is scaled relative to the data range per group, layer and panel. It would probably be better to scale it per layer. I'll be offline for a month or so, but I'll change it! 
Thanks!

**Comment by eliocamp** [comment]
Hey! I'm back! 

Should be fixed now!

![image](https://user-images.githubusercontent.com/8617595/53894693-50745880-400f-11e9-8c7e-0e4a2d8e6bca.png)
