### ISSUE TITLE
guide_grengrob

### ISSUE THREAD

**Issue by guillaumegeri** [eliocamp/metR#93]
Hi
When I try to load the metR package, R complains and tells me 

`Erreur : package or namespace load failed for ‘metR’:
 l'objet 'guide_gengrob' est introuvable pendant le chargement de l'espace de noms 'metR'`

I didn't find such an object. I tried to uninstall and re-install the package, without any success.
Any hint?
thanks ++

**Comment by eliocamp** [comment]
Strange. Seems an issue with the ggplot2 elements. My first guess would be to update ggplot2. 
I'm traveling and won't have access to a PC for some time, sorry!

**Comment by eliocamp** [comment]
@guillaumegeri Are you still having this issue?
